## Variables {.smaller}

::: {.incremental}
* A variable is a name that refers to a value
* You can use variables to store data in memory
* You can change the data stored in a variable at any time
* Allows you to reuse data without having to retype it
:::

## Variables
```{python}
#| echo: true
#| output-location: fragment
a = 1
print("The value of a is:")
print(a)
```

<br/>

```{python}
#| echo: true
#| output-location: fragment
b = 2
c = a + b
print("The value of c is:")
print(c)
```

## Variables
```{python}
#| echo: true
#| output-location: fragment
b = 2
a = b
print("The value of a is now:")
print(a)
```

<br/>

```{python}
#| echo: true
#| output-location: fragment
x, y = 10, 20

print("The value of x is:")
print(x)
print("The value of y is:")
print(y)
```

## Data types
::: {.incremental style="font-size: 80%;"}
* Different kinds of data are stored in different ways in memory
* You can use the `type()` function to find out what type of data a variable contains
:::

::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
print(type(1))
print(type(1.0))
print(type("Hello"))
```

:::

## Strings

::: {.incremental}
* A string is a sequence of characters
* Strings are enclosed in single or double quotes
* Used to represent text
:::

## Strings
```{python}
#| echo: true
#| output-location: fragment

a = "I want to learn "
b = 'Python!'

print(type(a))

print(a + b)
```

<br/>

::: {.fragment .fade-in style="font-size: 80%;"}
* Algebraic operations can have different meanings for different data types
    + Try `a*3` in the code above
:::

## f-strings
::: {.incremental}
* f-strings are a way to format strings
* Use `f` before the string
* Use `{variable}` to insert variables into the string
:::
::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
a = 42
print(f"The value of a is: {a}")
```
:::

## f-strings

You can also use f-strings to format numbers

::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
print(f"A rounded number: {8.333333333333333:.2f}")
```
:::

::: {.fragment .fade-in}
And compute values in the string
```{python}
#| echo: true
#| output-location: fragment
print(f"7 / 3 is: {7 / 3:.2f}")
``` 
:::

## Question

::: {.incremental}
* What is the type of...?
    + `100`
    + `'Dog'`
    + `3.14`
    + `print`
    + `False`
    + `'50'`
    + `None`
:::

## Question
* Can you add an **int** and a **float**?

::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
print(1 + 2.1)
```

:::

::: {.fragment .fade-in}
* What about an **int** and a **str**?
<br/>

```{python}
#| echo: true
#| output-location: fragment
#| error: true
print(1 + '2')
```

:::

## Lists {.smaller}

::::: {.columns}
::: {.column .incremental width="55%"}
* Ordered collection of values
* Enclosed in square brackets `[]`
* Any data type, including mixed types
* Indexed from 0 with square brackets `[]`
* Mutable (can be changed)
:::

::: {.column width="45%"}
:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
my_list = [1, 2.0, 'three', 'dog']
print(type(my_list))
```
::::

<br/>

:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
first = my_list[0]
second = my_list[1]
last = my_list[-1]
print(first, second, last)
```
::::

<br/>

:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
my_list.append('cat')
print(my_list)
```
::::

<br/>

:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
my_list[-1] = 'new_element'
print(my_list)
```
::::
:::
:::::
    
## Question {.smaller}
::::: {.columns}
::: {.column width="55%"}

:::: {.fragment .fade-in fragment-index=1}
* Find the third element from `my_list`?
::::

:::: {.fragment .fade-in fragment-index=4}
* Change the second element to `3.0`?
::::

:::: {.fragment .fade-in fragment-index=6}
* What happens if you request `my_list[5]`?
::::

:::

::: {.column width="45%"}
:::: {.fragment .fade-in fragment-index=2}
```{python}
#| echo: true
print(my_list)
```
::::

:::: {.fragment .fade-in fragment-index=3}
```{python}
#| echo: true
print(my_list[2])
```
::::

:::: {.fragment .fade-in fragment-index=5}
```{python}
#| echo: true
my_list[1] = 3.0
print(my_list)
```
::::

:::: {.fragment .fade-in fragment-index=7}
```{python}
#| echo: true
#| error: true
print(my_list[5])
```
::::

:::
:::::

## Tuples {.smaller}
::::: {.columns}
::: {.column .incremental width="55%"}
* Ordered collection of values
* Enclosed in parentheses `()`
* Any data type, including mixed types
* Immutable (cannot be changed)
* When would you use a tuple instead of a list?
:::

::: {.column width="45%"}
:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
#| error: true
my_tuple = (1, 2.0, 'cat', 'dog')

print(type(my_tuple))
print(my_tuple[2])
```
::::
:::

<br/>

:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
#| error: true
my_tuple[2] = 'new_element'
print(my_tuple)
```
::::
:::::

## Unpacking {.smaller}
::::: {.columns}
::: {.column .incremental width="55%"}
* Unpack a list or tuple into multiple variables
* Convenient for reassigning variables
:::

::: {.column width="45%"}
:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
my_tuple = (1, 2, 3, 4, 5)

a, b, c, d, e = my_tuple
print(a, b, c, d, e)
```
::::
:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
a, *b, c = my_tuple
print(a, b, c)
print(type(b))
```
::::
:::
:::::

## Question {.smaller}
::::: {.columns}
::: {.column width="55%"}

:::: {.fragment .fade-in fragment-index=1}
* How would you turn `my_list` into a tuple?
::::

:::: {.fragment .fade-in fragment-index=3}
* How would you turn `my_tuple` into a list?
::::

:::

::: {.column width="45%"}
:::: {.fragment .fade-in fragment-index=1}
```{python}
#| echo: true
my_tuple = (1, 2, 3, 4, 5)
my_list = [1, 2.0, 'three', 'dog']
```

<br/>

::::

:::: {.fragment .fade-in fragment-index=2}
```{python}
#| echo: true
my_list_as_tuple = tuple(my_list)
print(type(my_list_as_tuple))
```
::::

:::: {.fragment .fade-in fragment-index=4}
```{python}
#| echo: true
my_tuple_as_list = list(my_tuple)
print(type(my_tuple_as_list))
```
::::
:::
:::::

## Dictionaries {.smaller}
::::: {.columns}
::: {.column .incremental width="45%"}
* Collection of key-value pairs
* Enclosed in curly braces `{}`
* Keys are unique and immutable
:::

::: {.column width="55%"}
:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
my_dict = {
    'a_number': 1,
    'number_list': [1, 2, 3],
    'a_string': 'string',
    5.0: 'a float key'
}

print(my_dict.keys())
print(my_dict.values())
print(my_dict.items())
print(my_dict['a_string'])
print(my_dict[5.0])
```
::::
:::
:::::

## Question {.smaller}
::::: {.columns}
::: {.column width="45%"}
* What does `my_dict['a_number']` return?
:::

::: {.column width="55%"}
```{python}
#| echo: true
my_dict = {
    'a_number': 1,
    'number_list': [1, 2, 3],
    'a_string': 'string',
    'a_number': 2
}
```

:::: {.fragment fragment-index=1}
<br/>

```{python}
#| echo: true
#| output-location: fragment
print(my_dict['a_number'])
```
::::
:::
:::::

## Conditional statements {.smaller}
::::: {.columns}
::: {.column .incremental width="55%"}
* Execute code only if a condition is met
* Use `if`, `elif` (else if), and `else`
:::
::: {.column width="45%"}
:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
#| code-line-numbers: "|1|3|5|7,8|"

porridge_temp = 45

if porridge_temp < 40:
    print("Too cold!")
elif porridge_temp > 50:
    print("Too hot!")
else:
    print("Just right!")
```
::::
:::
:::::

## Question {.smaller}
* Write a loop that goes through the numbers 0 to 10
* For each number, print whether it is even or odd
    + Hint: use the modulus operator `%` and `==` to check for evenness

::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
#| code-line-numbers: "|1|2,3|4,5|"

for i in range(11):
    if i % 2 == 0:
        print(f"{i} is Even")
    else:
        print(f"{i} is Odd")
```
:::


## While loops {.smaller}
::::: {.columns}
::: {.column .incremental width="55%"}
* Do something while a condition is met
* Use `while`
:::

::: {.column width="45%"}
:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
expected_result = 10
result = 0
while not expected_result == result:
    print("Not there yet...")
    print(f"Result is {result}")
    result += 1
print("We got there!")
```
::::
:::

:::::

## For loops {.smaller}
::::: {.columns}
::: {.column .incremental width="55%"}
* Do the same thing multiple times
    + E.g.analyse N images
* Watch out for indentation!
    + Python uses indentation to define blocks of code
    + Usually 2-4 spaces (or a tab)
:::

::: {.column width="45%"}
:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment

for i in [0, 1, 2]:
    print(i)
```
::::

<br/>

:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment

for i in range(5):
    print(i)
```
::::
:::
:::::

## For loops {.smaller}
::::: {.columns}
::: {.column .incremental width="55%"}
* You can loop over any iterable
* Use `_` if you don't need the loop variable
* `enumerate()` gives you the index and the value
* `range()` generates a sequence of numbers
    + `range(n)` from 0 to n-1
    + `range(a, b)` from a to b-1
    + `range(a, b, step)` from a to b-1 with jumps of step
:::
::: {.column width="45%"}
:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
my_list = ['cat', 'dog', 'rabbit']
for animal in my_list:
    print("My pet is a: " + animal)
```
::::

<br/>

:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
for _ in range(3):
    print("Hello!")
```
::::

<br/>

:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
for index, animal in enumerate(my_list):
    print(f"My pet #{index} is a: {animal}")
```
::::
:::
:::::

## Break and continue statements {.smaller}
::::: {.columns}
::: {.column .incremental width="55%"}
* `break` out of a loop
* `continue` to the next iteration
:::

::: {.column width="45%"}
:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
for i in range(10):
    if i == 5:
        break
    print(i)
```
::::

:::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
for i in range(10):
    if i == 5:
        continue
    print(i)
```
::::
:::

:::::



## Question {.smaller}
::: {.fragment .fade-in }
* Create a list of integers from 0 to 5
* Use a loop to find the sum of the squares of the integers in the list
* Print the result
:::
::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment

numbers = [0, 1, 2, 3, 4, 5]
sum_of_squares = 0

for number in numbers:
    sum_of_squares = sum_of_squares + number**2

print(sum_of_squares)
```
:::

<br/>

::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
#| code-line-numbers: "|5|"
numbers = [0, 1, 2, 3, 4, 5]
sum_of_squares = 0

for number in numbers:
    sum_of_squares += number**2

print(sum_of_squares)
```
:::

## Question {.smaller}
<!-- exercise with while loop and break statement -->
::: {.fragment .fade-in }
* Write a loop that only prints numbers divisible by 3 until you get to 30
* Use a while loop
:::
::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
number = 0
while number < 30:
    if number % 3 == 0:
        print(number)
    number += 1
```
:::

## List comprehensions {.smaller}
::::: {.columns}
::: {.column width="55%"}

:::: {.fragment .fade-in fragment-index=1}
* Concise way to create lists
* `[expression for item in iterable]`
::::

:::: {.fragment .fade-in fragment-index=4}
* Can include conditions
* `[expression for item in iterable if condition]`
::::

:::
::: {.column width="45%"}
:::: {.fragment .fade-in fragment-index=2}
Classic:
```{python}
#| echo: true

squares = []
for num in range(5):
    squares.append(num**2)
print(squares)
```

::::
:::: {.fragment .fade-in fragment-index=3}
List comprehension:
```{python}
#| echo: true
squares = [num**2 for num in range(5)]
print(squares)
```
::::
:::
:::: {.fragment .fade-in fragment-index=5}
With condition:
```{python}
#| echo: true
#| output-location: fragment
large_squares = [num**2 for num in range(10) if num > 3]
print(large_squares)
```
::::
:::::

## Question {.smaller}
* Create a list of square even numbers from 1 to 10 using a list comprehension

::: {.fragment .fade-in}
```{python}
#| echo: true
#| output-location: fragment
even_squares = [num**2 for num in range(1, 11) if num % 2 == 0]
print(even_squares)
```
:::

